name: fernstack
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  go_router: ^10.1.2
  google_sign_in: ^6.1.5
  talker_dio_logger: ^2.3.0
  talker_logger: ^3.1.0
  flutter_secure_storage: ^9.0.0
  simple_icons: ^7.10.0
  icons_plus: ^4.0.0
  rive: ^0.11.17
  cupertino_icons: ^1.0.6
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.4

flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image: "assets/images/fernsplash.png"

  android_12:
    image: assets/images/fernsplash.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/rive/
    - assets/
  